### ISSUE TITLE
Training the Big Bird model on classification task

### ISSUE THREAD

**Issue by bhakti-visotrust** [lkwate/legal-information-retrieval#1]
Are you planning on training the Big Bird model on a classification task for Legal dataset? The current model is imported from AutoModelForMaskedLM class and isn't specific to classification.

I want to use transfer learning and fine tune the Legal Big Bird model on my smaller data with language similar to legal documents. If you plan on training for classification (if not already) please let me know.

**Comment by lkwate** [comment]
No. I only continued the MLM training of BigBird on legal documents. That is a good idea to fine-tune on text classification task :+1: .

**Comment by bhakti-visotrust** [comment]
When fine-tuning it on classification task I get these warnings:
```
Some weights of the model checkpoint at lkwate/legal-bigbird-us were not used when initializing BigBirdForSequenceClassification: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing BigBirdForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BigBirdForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BigBirdForSequenceClassification were not initialized from the model checkpoint at lkwate/legal-bigbird-us and are newly initialized: ['classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.dense.bias']
```
and I am importing the model as:
`model = BigBirdForSequenceClassification.from_pretrained("lkwate/legal-bigbird-us")`

**Comment by lkwate** [comment]
It is normal. When you will train, save and re-load your model, you will not get this warning anymore.
